#Redis数据库连接配置
redis.dev.host=redis-16629.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
redis.dev.port=16629
redis.dev.pass=oSSV8ecVl28CjQyum2aBTpncqqtN8Bkv
redis.pro.host=
redis.pro.port=
redis.pro.pass=
redis.maxIdle=50
redis.maxWait=1000
redis.testOnBorrow=true